### ISSUE TITLE
Can‘t save to mongoDB

### ISSUE THREAD

**Issue by OrangeShen** [Python3WebSpider/IGetGet#1]
连接MongoDB的时候出现问题，在使用：
client = MongoClient('localhost')
创建一个实例的过程中，产生了如下错误：
TypeError: MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True) **is not a callable object**

**Comment by xiaomengdashi** [comment]
添加端口号
client = pymongo.MongoClient('localhost',prot=27017)

**Comment by monkey-wenjun** [comment]
```
Addon error: Traceback (most recent call last):
  File "/Users/wenjun/PycharmProjects/python3study/venv/lib/python3.7/site-packages/mitmproxy/addonmanager.py", line 42, in safecall
    yield
  File "/Users/wenjun/PycharmProjects/python3study/venv/lib/python3.7/site-packages/mitmproxy/addons/script.py", line 102, in loadscript
    ctx.master.addons.register(ns)
  File "/Users/wenjun/PycharmProjects/python3study/venv/lib/python3.7/site-packages/mitmproxy/addonmanager.py", line 161, in register
    self.master.commands.collect_commands(a)
  File "/Users/wenjun/PycharmProjects/python3study/venv/lib/python3.7/site-packages/mitmproxy/command.py", line 144, in collect_commands
    self.add(o.command_path, o)
  File "/Users/wenjun/PycharmProjects/python3study/venv/lib/python3.7/site-packages/mitmproxy/command.py", line 151, in add
    self.commands[path] = Command(self, path, func)
  File "/Users/wenjun/PycharmProjects/python3study/venv/lib/python3.7/site-packages/mitmproxy/command.py", line 51, in __init__
    sig = inspect.signature(self.func)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 3070, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 2820, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 2201, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True) is not a callable object
```

**Comment by goodbad3** [comment]
E:\>mitmdump -s script.py
Loading script script.py
Addon error: Traceback (most recent call last):
  File "e:\python36\lib\site-packages\mitmproxy\addonmanager.py", line 42, in safecall
    yield
  File "e:\python36\lib\site-packages\mitmproxy\addons\script.py", line 102, in loadscript
    ctx.master.addons.register(ns)
  File "e:\python36\lib\site-packages\mitmproxy\addonmanager.py", line 161, in register
    self.master.commands.collect_commands(a)
  File "e:\python36\lib\site-packages\mitmproxy\command.py", line 144, in collect_commands
    self.add(o.command_path, o)
  File "e:\python36\lib\site-packages\mitmproxy\command.py", line 151, in add
    self.commands[path] = Command(self, path, func)
  File "e:\python36\lib\site-packages\mitmproxy\command.py", line 51, in __init__
    sig = inspect.signature(self.func)
  File "e:\python36\lib\inspect.py", line 3052, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "e:\python36\lib\inspect.py", line 2802, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "e:\python36\lib\inspect.py", line 2186, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True) is not a callable object

Proxy server listening at http://*:8080

**Comment by goodbad3** [comment]
@OrangeShen @monkey-wenjun 成功没？？？

**Comment by LittleBoy1993** [comment]
@OrangeShen @monkey-wenjun @goodbad3 有大神解决了吗...

**Comment by goodbad3** [comment]
@OrangeShen @monkey-wenjun @LittleBoy1993 @Germey 
mongodb吧一定是不能存的
import json

from mitmproxy import ctx
 
def write_to_file(content):
    with open('result.txt', 'a', encoding='utf-8') as f:
        f.write(json.dumps(content, ensure_ascii=False) + '\n')


def response(flow):
    global collection
    url = 'https://dedao.igetget.com/v3/discover/bookList'
    if flow.request.url.startswith(url):
        text = flow.response.text
        data = json.loads(text)
        books = data.get('c').get('list')
        for book in books:
            
            data = {
                'title': book.get('operating_title'),
                'cover': book.get('cover'),
                'summary': book.get('other_share_summary'),
                'price': book.get('price')
            }
            
            ctx.log.info(str(book))
            write_to_file(data)

**Comment by goodbad3** [comment]
有会存mongodb的CALL ME

**Comment by goodbad3** [comment]
可以先存成其他，象是.txt, 然后再存mongo
还可以自定义 __call__()方法， 变成可调运对象

**Comment by Sagat0219** [comment]
@goodbad3 @OrangeShen @monkey-wenjun @LittleBoy1993 
将mongodb包装到类里，然后在response函数里调用类进行数据库操作。可以解决此问题。已验证。

参考：https://www.zhihu.com/question/279829142

**Comment by aesdhj** [comment]
> @goodbad3 @OrangeShen @monkey-wenjun @LittleBoy1993
> 将mongodb包装到类里，然后在response函数里调用类进行数据库操作。可以解决此问题。已验证。
> 
> 参考：https://www.zhihu.com/question/279829142

我也在看这本书，为这本书建了一个QQ群805370297，方便大家讨论

**Comment by arronking93** [comment]
> @goodbad3 @OrangeShen @monkey-wenjun @LittleBoy1993
> 将mongodb包装到类里，然后在response函数里调用类进行数据库操作。可以解决此问题。已验证。
> 
> 参考：https://www.zhihu.com/question/279829142

正解，谢谢，我猜是api的问题了

**Comment by arronking93** [comment]
附上代码：
import json
import pymongo
from mitmproxy import ctx

class DedaoMongo:
    def __init__(self):
        self.client = pymongo.MongoClient(host='localhost', port=27017)
        self.db = self.client['igetget']
        self.collection = self.db['books']

    def update_book(self, flow):
        url = 'https://dedao.igetget.com/v3/discover/bookList'
        if flow.request.url.startswith(url):
            text = flow.response.text
            data = json.loads(text)
            books = data.get('c').get('list')
            for book in books:
                data = {
                    'title': book.get('operating_title'),
                    'price': book.get('price'),
                    'cover': book.get('cover'),
                    'summary': book.get('other_share_summary'),
                }
                ctx.log.info(str(data))
                self.collection.insert(data)

def response(flow):
    DedaoMongo().update_book(flow)

**Comment by gamely** [comment]
import json
from mitmproxy import ctx
import pymongo

class DedaoMongo(object):
    def __init__(self):
        self.client = pymongo.MongoClient('localhost')
        self.db = self.client['dedao']
        self.collection = self.db['booklists']
    def update_book(self,book_info):
        self.collection.insert(book_info)
dedaomongo=DedaoMongo()
def response(flow):  
    #global collection
    url="https://m.igetget.com/hybrid/api/ebook/list"
    if flow.request.url.startswith(url):
        text = flow.response.text
        data = json.loads(text)
        books = data["data"]
        for book in books:
            
            book_info ={
                'title':book.get('operatingTitle'),
                'cover':book.get('cover'),
                'price':book.get('price'),
                'summary':book.get('otherShareSummary'),
                'year':book.get('epub')
                }
            ctx.log.info(str(book_info))
            dedaomongo.update_book(book_info)

**Comment by gamely** [comment]
import json
from mitmproxy import ctx
import pymongo

class DedaoMongo(object):
    def __init__(self):
        self.client = pymongo.MongoClient('localhost')
        self.db = self.client['dedao']
        self.collection = self.db['booklists']
    def update_book(self,book_info):
        self.collection.insert(book_info)
dedaomongo=DedaoMongo()
def response(flow):  
    #global collection
    url="https://m.igetget.com/hybrid/api/ebook/list"
    if flow.request.url.startswith(url):
        text = flow.response.text
        data = json.loads(text)
        books = data["data"]
        for book in books:
            
            book_info ={
                'title':book.get('operatingTitle'),
                'cover':book.get('cover'),
                'price':book.get('price'),
                'summary':book.get('otherShareSummary'),
                'year':book.get('epub')
                }
            ctx.log.info(str(book_info))
            dedaomongo.update_book(book_info)
