### ISSUE TITLE
无法描述的错误

### ISSUE THREAD

**Issue by goodbad3** [Python3WebSpider/IGetGet#3]
xpected EOF')",)
192.168.1.100:38426: clientdisconnect
192.168.1.100:38424: clientdisconnect
192.168.1.100:38425: clientdisconnect
192.168.1.100:38427: clientconnect
192.168.1.100:38428: clientconnect
192.168.1.100:38428: CONNECT piccdn.igetget.com:443
 << Cannot establish TLS with client (sni: piccdn.igetget.com): TlsException("SSL handshake error: SysCallError(-1, 'Unexpected EOF')",)
192.168.1.100:38427: CONNECT piccdn.igetget.com:443
 << Cannot establish TLS with client (sni: piccdn.igetget.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)",)
192.168.1.100:38428: clientdisconnect
192.168.1.100:38427: clientdisconnect
192.168.1.100:38429: clientconnect
192.168.1.100:38430: clientconnect
192.168.1.100:38431: clientconnect
192.168.1.100:38432: clientconnect
192.168.1.100:38433: clientconnect
192.168.1.100:38432: GET http://59.49.91.44/pc/misc/files/20170111/7b893b51738848a49c9759564f9ad429.png
                  << 200 OK 2.64k
192.168.1.100:38434: clientconnect
192.168.1.100:38429: GET https://pub.idqqimg.com/pc/misc/files/20160909/93ab99177daa4ed1a8a7114fe9c0682d.png
                  << 200 OK 1.87k
192.168.1.100:38431: GET https://pub.idqqimg.com/pc/misc/files/20160909/65e35d72a9be4003b561ffbe7ebc4ca5.png
                  << 200 OK 1.51k

**Comment by aesdhj** [comment]
<< Cannot establish TLS with client (sni: piccdn.igetget.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)",)
请问一下这个后来怎么解决的

**Comment by ghost** [comment]
也是 Cannot establish TLS with client, TlsException  SSL handkshake error

**Comment by zhangyunboxj** [comment]
哪位可以告诉我一下这个问题怎么解决啊？找了半天也没有找到方法

**Comment by Germey** [comment]
你看看是不是证书问题，或者说是安卓 7.0 版本的问题？
